name = "RobustVisualGeometry"
uuid = "48970fad-9a21-401c-bf6c-679fa4f2bd7f"
version = "0.1.0"
authors = ["James Pritts <jbpritts@gmail.com>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
VisualGeometryCore = "297d53b8-c8d7-4cd7-a9af-68e656508a81"

[sources]
VisualGeometryCore = {path = "../BlobBoards.jl/deps/VisualGeometryCore"}

[compat]
Distributions = "0.25"
FixedSizeArrays = "1.2.0"
StaticArrays = "1"
StructArrays = "0.7"
VisualGeometryCore = "0.1"
julia = "1.12"

[extras]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ForwardDiff"]
